# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T10:31:00+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr


class AccessDeniedException(RootModel[Any]):
    root: Any


class AccountId(RootModel[constr(pattern=r'^[0-9]+$', min_length=12, max_length=12)]):
    root: constr(pattern=r'^[0-9]+$', min_length=12, max_length=12)


class AccountIdExtendedList(RootModel[List[AccountId]]):
    root: List[AccountId] = Field(..., max_length=200, min_length=1)


class AccountIdList(RootModel[List[AccountId]]):
    root: List[AccountId] = Field(..., max_length=50, min_length=1)


class Boolean(RootModel[bool]):
    root: bool


class ByteValue(RootModel[int]):
    root: int


class ConflictException(RootModel[Any]):
    root: Any


class DatasourcePackage(Enum):
    DETECTIVE_CORE = 'DETECTIVE_CORE'
    EKS_AUDIT = 'EKS_AUDIT'


class DatasourcePackageIngestState(Enum):
    STARTED = 'STARTED'
    STOPPED = 'STOPPED'
    DISABLED = 'DISABLED'


class DatasourcePackageIngestStates(
    RootModel[Optional[Dict[str, DatasourcePackageIngestState]]]
):
    root: Optional[Dict[str, DatasourcePackageIngestState]] = None


class DatasourcePackageList(RootModel[List[DatasourcePackage]]):
    root: List[DatasourcePackage] = Field(..., max_length=25, min_length=1)


class DescribeOrganizationConfigurationResponse(BaseModel):
    AutoEnable: Optional[Boolean] = None


class EmailAddress(
    RootModel[
        constr(
            pattern=r'^.+@(?:(?:(?!-)[A-Za-z0-9-]{1,62})?[A-Za-z0-9]{1}\.)+[A-Za-z]{2,6}$',
            min_length=1,
            max_length=64,
        )
    ]
):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: constr(
        pattern=r'^.+@(?:(?:(?!-)[A-Za-z0-9-]{1,62})?[A-Za-z0-9]{1}\.)+[A-Za-z]{2,6}$',
        min_length=1,
        max_length=64,
    )


class EmailMessage(RootModel[constr(min_length=1, max_length=1000)]):
    root: constr(min_length=1, max_length=1000)


class EnableOrganizationAdminAccountRequest(BaseModel):
    AccountId_1: AccountId = Field(..., alias='AccountId')


class GraphArn(
    RootModel[
        constr(
            pattern=r'^arn:aws[-\w]{0,10}?:detective:[-\w]{2,20}?:\d{12}?:graph:[abcdef\d]{32}?$'
        )
    ]
):
    root: constr(
        pattern=r'^arn:aws[-\w]{0,10}?:detective:[-\w]{2,20}?:\d{12}?:graph:[abcdef\d]{32}?$'
    )


class GraphArnList(RootModel[List[GraphArn]]):
    root: List[GraphArn] = Field(..., max_length=50, min_length=1)


class InternalServerException(RootModel[Any]):
    root: Any


class InvitationType(Enum):
    INVITATION = 'INVITATION'
    ORGANIZATION = 'ORGANIZATION'


class ListTagsForResourceRequest(BaseModel):
    pass


class MemberDisabledReason(Enum):
    VOLUME_TOO_HIGH = 'VOLUME_TOO_HIGH'
    VOLUME_UNKNOWN = 'VOLUME_UNKNOWN'


class MemberResultsLimit(RootModel[conint(ge=1, le=200)]):
    root: conint(ge=1, le=200)


class MemberStatus(Enum):
    INVITED = 'INVITED'
    VERIFICATION_IN_PROGRESS = 'VERIFICATION_IN_PROGRESS'
    VERIFICATION_FAILED = 'VERIFICATION_FAILED'
    ENABLED = 'ENABLED'
    ACCEPTED_BUT_DISABLED = 'ACCEPTED_BUT_DISABLED'


class PaginationToken(RootModel[constr(min_length=1, max_length=1024)]):
    root: constr(min_length=1, max_length=1024)


class Percentage(RootModel[float]):
    root: float


class RejectInvitationRequest(BaseModel):
    GraphArn_1: GraphArn = Field(..., alias='GraphArn')


class ResourceNotFoundException(RootModel[Any]):
    root: Any


class ServiceQuotaExceededException(RootModel[Any]):
    root: Any


class StartMonitoringMemberRequest(BaseModel):
    AccountId_1: AccountId = Field(..., alias='AccountId')
    GraphArn_1: GraphArn = Field(..., alias='GraphArn')


class TagKey(
    RootModel[
        constr(pattern=r'^(?!aws:)[a-zA-Z+-=._:/]+$', min_length=1, max_length=128)
    ]
):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: constr(pattern=r'^(?!aws:)[a-zA-Z+-=._:/]+$', min_length=1, max_length=128)


class TagKeyList(RootModel[List[TagKey]]):
    root: List[TagKey] = Field(..., max_length=50, min_length=1)


class TagResourceResponse(BaseModel):
    pass


class TagValue(RootModel[constr(max_length=256)]):
    root: constr(max_length=256)


class Timestamp(RootModel[datetime]):
    root: datetime


class TimestampForCollection(BaseModel):
    Timestamp_1: Optional[Timestamp] = Field(None, alias='Timestamp')


class TooManyRequestsException(RootModel[Any]):
    root: Any


class UnprocessedReason(RootModel[str]):
    root: str


class UntagResourceRequest(BaseModel):
    pass


class UntagResourceResponse(BaseModel):
    pass


class UpdateDatasourcePackagesRequest(BaseModel):
    DatasourcePackages: DatasourcePackageList
    GraphArn_1: GraphArn = Field(..., alias='GraphArn')


class UpdateOrganizationConfigurationRequest(BaseModel):
    AutoEnable: Optional[Boolean] = None
    GraphArn_1: GraphArn = Field(..., alias='GraphArn')


class ValidationException(RootModel[Any]):
    root: Any


class GraphPostRequest(BaseModel):
    Tags: Optional[Dict[str, TagValue]] = Field(
        None,
        description='The tags to assign to the new behavior graph. You can add up to 50 tags. For each tag, you provide the tag key and the tag value. Each tag key can contain up to 128 characters. Each tag value can contain up to 256 characters.',
    )


class GraphDatasourcesGetPostRequest(BaseModel):
    AccountIds: List[AccountId] = Field(
        ...,
        description='The list of Amazon Web Services accounts to get data source package information on.',
        max_length=200,
        min_length=1,
    )
    GraphArn: constr(
        pattern=r'^arn:aws[-\w]{0,10}?:detective:[-\w]{2,20}?:\d{12}?:graph:[abcdef\d]{32}?$'
    ) = Field(..., description='The ARN of the behavior graph.')


class GraphDatasourcesListPostRequest(BaseModel):
    GraphArn: constr(
        pattern=r'^arn:aws[-\w]{0,10}?:detective:[-\w]{2,20}?:\d{12}?:graph:[abcdef\d]{32}?$'
    ) = Field(..., description='The ARN of the behavior graph.')
    MaxResults: Optional[conint(ge=1, le=200)] = Field(
        None, description='The maximum number of results to return.'
    )
    NextToken: Optional[constr(min_length=1, max_length=1024)] = Field(
        None,
        description='For requests to get the next page of results, the pagination token that was returned with the previous set of results. The initial request does not include a pagination token.',
    )


class GraphDatasourcesUpdatePostRequest(BaseModel):
    DatasourcePackages: List[DatasourcePackage] = Field(
        ...,
        description='The data source package start for the behavior graph.',
        max_length=25,
        min_length=1,
    )
    GraphArn: constr(
        pattern=r'^arn:aws[-\w]{0,10}?:detective:[-\w]{2,20}?:\d{12}?:graph:[abcdef\d]{32}?$'
    ) = Field(..., description='The ARN of the behavior graph.')


class GraphMemberMonitoringstatePostRequest(BaseModel):
    AccountId: constr(pattern=r'^[0-9]+$', min_length=12, max_length=12) = Field(
        ...,
        description='<p>The account ID of the member account to try to enable.</p> <p>The account must be an invited member account with a status of <code>ACCEPTED_BUT_DISABLED</code>. </p>',
    )
    GraphArn: constr(
        pattern=r'^arn:aws[-\w]{0,10}?:detective:[-\w]{2,20}?:\d{12}?:graph:[abcdef\d]{32}?$'
    ) = Field(..., description='The ARN of the behavior graph.')


class GraphMembersGetPostRequest(BaseModel):
    AccountIds: List[AccountId] = Field(
        ...,
        description='<p>The list of Amazon Web Services account identifiers for the member account for which to return member details. You can request details for up to 50 member accounts at a time.</p> <p>You cannot use <code>GetMembers</code> to retrieve information about member accounts that were removed from the behavior graph.</p>',
        max_length=50,
        min_length=1,
    )
    GraphArn: constr(
        pattern=r'^arn:aws[-\w]{0,10}?:detective:[-\w]{2,20}?:\d{12}?:graph:[abcdef\d]{32}?$'
    ) = Field(
        ...,
        description='The ARN of the behavior graph for which to request the member details.',
    )


class GraphMembersListPostRequest(BaseModel):
    GraphArn: constr(
        pattern=r'^arn:aws[-\w]{0,10}?:detective:[-\w]{2,20}?:\d{12}?:graph:[abcdef\d]{32}?$'
    ) = Field(
        ...,
        description='The ARN of the behavior graph for which to retrieve the list of member accounts.',
    )
    MaxResults: Optional[conint(ge=1, le=200)] = Field(
        None,
        description='The maximum number of member accounts to include in the response. The total must be less than the overall limit on the number of results to return, which is currently 200.',
    )
    NextToken: Optional[constr(min_length=1, max_length=1024)] = Field(
        None,
        description='For requests to retrieve the next page of member account results, the pagination token that was returned with the previous page of results. The initial request does not include a pagination token.',
    )


class GraphMembersRemovalPostRequest(BaseModel):
    AccountIds: List[AccountId] = Field(
        ...,
        description='The list of Amazon Web Services account identifiers for the member accounts to remove from the behavior graph. You can remove up to 50 member accounts at a time.',
        max_length=50,
        min_length=1,
    )
    GraphArn: constr(
        pattern=r'^arn:aws[-\w]{0,10}?:detective:[-\w]{2,20}?:\d{12}?:graph:[abcdef\d]{32}?$'
    ) = Field(..., description='The ARN of the behavior graph to remove members from.')


class GraphRemovalPostRequest(BaseModel):
    GraphArn: constr(
        pattern=r'^arn:aws[-\w]{0,10}?:detective:[-\w]{2,20}?:\d{12}?:graph:[abcdef\d]{32}?$'
    ) = Field(..., description='The ARN of the behavior graph to disable.')


class GraphsListPostRequest(BaseModel):
    MaxResults: Optional[conint(ge=1, le=200)] = Field(
        None,
        description='The maximum number of graphs to return at a time. The total must be less than the overall limit on the number of results to return, which is currently 200.',
    )
    NextToken: Optional[constr(min_length=1, max_length=1024)] = Field(
        None,
        description='For requests to get the next page of results, the pagination token that was returned with the previous set of results. The initial request does not include a pagination token.',
    )


class InvitationPutRequest(BaseModel):
    GraphArn: constr(
        pattern=r'^arn:aws[-\w]{0,10}?:detective:[-\w]{2,20}?:\d{12}?:graph:[abcdef\d]{32}?$'
    ) = Field(
        ...,
        description='<p>The ARN of the behavior graph that the member account is accepting the invitation for.</p> <p>The member account status in the behavior graph must be <code>INVITED</code>.</p>',
    )


class InvitationRemovalPostRequest(BaseModel):
    GraphArn: constr(
        pattern=r'^arn:aws[-\w]{0,10}?:detective:[-\w]{2,20}?:\d{12}?:graph:[abcdef\d]{32}?$'
    ) = Field(
        ...,
        description="<p>The ARN of the behavior graph to reject the invitation to.</p> <p>The member account's current member status in the behavior graph must be <code>INVITED</code>.</p>",
    )


class InvitationsListPostRequest(BaseModel):
    MaxResults: Optional[conint(ge=1, le=200)] = Field(
        None,
        description='The maximum number of behavior graph invitations to return in the response. The total must be less than the overall limit on the number of results to return, which is currently 200.',
    )
    NextToken: Optional[constr(min_length=1, max_length=1024)] = Field(
        None,
        description='For requests to retrieve the next page of results, the pagination token that was returned with the previous page of results. The initial request does not include a pagination token.',
    )


class MembershipDatasourcesGetPostRequest(BaseModel):
    GraphArns: List[GraphArn] = Field(
        ..., description='The ARN of the behavior graph.', max_length=50, min_length=1
    )


class MembershipRemovalPostRequest(BaseModel):
    GraphArn: constr(
        pattern=r'^arn:aws[-\w]{0,10}?:detective:[-\w]{2,20}?:\d{12}?:graph:[abcdef\d]{32}?$'
    ) = Field(
        ...,
        description="<p>The ARN of the behavior graph to remove the member account from.</p> <p>The member account's member status in the behavior graph must be <code>ENABLED</code>.</p>",
    )


class OrgsAdminAccountslistPostRequest(BaseModel):
    MaxResults: Optional[conint(ge=1, le=200)] = Field(
        None, description='The maximum number of results to return.'
    )
    NextToken: Optional[constr(min_length=1, max_length=1024)] = Field(
        None,
        description='For requests to get the next page of results, the pagination token that was returned with the previous set of results. The initial request does not include a pagination token.',
    )


class OrgsDescribeOrganizationConfigurationPostRequest(BaseModel):
    GraphArn: constr(
        pattern=r'^arn:aws[-\w]{0,10}?:detective:[-\w]{2,20}?:\d{12}?:graph:[abcdef\d]{32}?$'
    ) = Field(..., description='The ARN of the organization behavior graph.')


class OrgsEnableAdminAccountPostRequest(BaseModel):
    AccountId: constr(pattern=r'^[0-9]+$', min_length=12, max_length=12) = Field(
        ...,
        description='The Amazon Web Services account identifier of the account to designate as the Detective administrator account for the organization.',
    )


class OrgsUpdateOrganizationConfigurationPostRequest(BaseModel):
    AutoEnable: Optional[bool] = Field(
        None,
        description='Indicates whether to automatically enable new organization accounts as member accounts in the organization behavior graph.',
    )
    GraphArn: constr(
        pattern=r'^arn:aws[-\w]{0,10}?:detective:[-\w]{2,20}?:\d{12}?:graph:[abcdef\d]{32}?$'
    ) = Field(..., description='The ARN of the organization behavior graph.')


class TagsResourceArnPostRequest(BaseModel):
    Tags: Dict[str, TagValue] = Field(
        ...,
        description='The tags to assign to the behavior graph. You can add up to 50 tags. For each tag, you provide the tag key and the tag value. Each tag key can contain up to 128 characters. Each tag value can contain up to 256 characters.',
    )


class TagKeys(RootModel[List[TagKey]]):
    root: List[TagKey] = Field(..., max_length=50, min_length=1)


class AcceptInvitationRequest(BaseModel):
    GraphArn_1: GraphArn = Field(..., alias='GraphArn')


class Account(BaseModel):
    AccountId_1: AccountId = Field(..., alias='AccountId')
    EmailAddress_1: EmailAddress = Field(..., alias='EmailAddress')


class AccountList(RootModel[List[Account]]):
    root: List[Account] = Field(..., max_length=50, min_length=1)


class Administrator(BaseModel):
    AccountId_1: Optional[AccountId] = Field(None, alias='AccountId')
    DelegationTime: Optional[Timestamp] = None
    GraphArn_1: Optional[GraphArn] = Field(None, alias='GraphArn')


class AdministratorList(RootModel[List[Administrator]]):
    root: List[Administrator]


class BatchGetGraphMemberDatasourcesRequest(BaseModel):
    AccountIds: AccountIdExtendedList
    GraphArn_1: GraphArn = Field(..., alias='GraphArn')


class BatchGetMembershipDatasourcesRequest(BaseModel):
    GraphArns: GraphArnList


class CreateGraphResponse(BaseModel):
    GraphArn_1: Optional[GraphArn] = Field(None, alias='GraphArn')


class CreateMembersRequest(BaseModel):
    Accounts: AccountList
    DisableEmailNotification: Optional[Boolean] = None
    GraphArn_1: GraphArn = Field(..., alias='GraphArn')
    Message: Optional[EmailMessage] = None


class DatasourcePackageUsageInfo(BaseModel):
    VolumeUsageInBytes: Optional[ByteValue] = None
    VolumeUsageUpdateTime: Optional[Timestamp] = None


class DeleteGraphRequest(BaseModel):
    GraphArn_1: GraphArn = Field(..., alias='GraphArn')


class DeleteMembersRequest(BaseModel):
    AccountIds: AccountIdList
    GraphArn_1: GraphArn = Field(..., alias='GraphArn')


class DescribeOrganizationConfigurationRequest(BaseModel):
    GraphArn_1: GraphArn = Field(..., alias='GraphArn')


class DisassociateMembershipRequest(BaseModel):
    GraphArn_1: GraphArn = Field(..., alias='GraphArn')


class GetMembersRequest(BaseModel):
    AccountIds: AccountIdList
    GraphArn_1: GraphArn = Field(..., alias='GraphArn')


class Graph(BaseModel):
    Arn: Optional[GraphArn] = None
    CreatedTime: Optional[Timestamp] = None


class GraphList(RootModel[List[Graph]]):
    root: List[Graph]


class LastIngestStateChangeDates(
    RootModel[Optional[Dict[str, TimestampForCollection]]]
):
    root: Optional[Dict[str, TimestampForCollection]] = None


class ListDatasourcePackagesRequest(BaseModel):
    GraphArn_1: GraphArn = Field(..., alias='GraphArn')
    MaxResults: Optional[MemberResultsLimit] = None
    NextToken: Optional[PaginationToken] = None


class ListGraphsRequest(BaseModel):
    MaxResults: Optional[MemberResultsLimit] = None
    NextToken: Optional[PaginationToken] = None


class ListGraphsResponse(BaseModel):
    GraphList_1: Optional[GraphList] = Field(None, alias='GraphList')
    NextToken: Optional[PaginationToken] = None


class ListInvitationsRequest(BaseModel):
    MaxResults: Optional[MemberResultsLimit] = None
    NextToken: Optional[PaginationToken] = None


class ListMembersRequest(BaseModel):
    GraphArn_1: GraphArn = Field(..., alias='GraphArn')
    MaxResults: Optional[MemberResultsLimit] = None
    NextToken: Optional[PaginationToken] = None


class ListOrganizationAdminAccountsRequest(BaseModel):
    MaxResults: Optional[MemberResultsLimit] = None
    NextToken: Optional[PaginationToken] = None


class ListOrganizationAdminAccountsResponse(BaseModel):
    Administrators: Optional[AdministratorList] = None
    NextToken: Optional[PaginationToken] = None


class TagMap(RootModel[Optional[Dict[str, TagValue]]]):
    root: Optional[Dict[str, TagValue]] = None


class TagResourceRequest(BaseModel):
    Tags: TagMap


class UnprocessedAccount(BaseModel):
    AccountId_1: Optional[AccountId] = Field(None, alias='AccountId')
    Reason: Optional[UnprocessedReason] = None


class UnprocessedAccountList(RootModel[List[UnprocessedAccount]]):
    root: List[UnprocessedAccount]


class UnprocessedGraph(BaseModel):
    GraphArn_1: Optional[GraphArn] = Field(None, alias='GraphArn')
    Reason: Optional[UnprocessedReason] = None


class UnprocessedGraphList(RootModel[List[UnprocessedGraph]]):
    root: List[UnprocessedGraph]


class VolumeUsageByDatasourcePackage(
    RootModel[Optional[Dict[str, DatasourcePackageUsageInfo]]]
):
    root: Optional[Dict[str, DatasourcePackageUsageInfo]] = None


class GraphMembersPostRequest(BaseModel):
    Accounts: List[Account] = Field(
        ...,
        description='The list of Amazon Web Services accounts to invite or to enable. You can invite or enable up to 50 accounts at a time. For each invited account, the account list contains the account identifier and the Amazon Web Services account root user email address. For organization accounts in the organization behavior graph, the email address is not required.',
        max_length=50,
        min_length=1,
    )
    DisableEmailNotification: Optional[bool] = Field(
        None,
        description='<p>if set to <code>true</code>, then the invited accounts do not receive email notifications. By default, this is set to <code>false</code>, and the invited accounts receive email notifications.</p> <p>Organization accounts in the organization behavior graph do not receive email notifications.</p>',
    )
    GraphArn: constr(
        pattern=r'^arn:aws[-\w]{0,10}?:detective:[-\w]{2,20}?:\d{12}?:graph:[abcdef\d]{32}?$'
    ) = Field(..., description='The ARN of the behavior graph.')
    Message: Optional[constr(min_length=1, max_length=1000)] = Field(
        None,
        description='Customized message text to include in the invitation email message to the invited member accounts.',
    )


class CreateGraphRequest(BaseModel):
    Tags: Optional[TagMap] = None


class DatasourcePackageIngestDetail(BaseModel):
    DatasourcePackageIngestState_1: Optional[DatasourcePackageIngestState] = Field(
        None, alias='DatasourcePackageIngestState'
    )
    LastIngestStateChange: Optional[LastIngestStateChangeDates] = None


class DatasourcePackageIngestDetails(
    RootModel[Optional[Dict[str, DatasourcePackageIngestDetail]]]
):
    root: Optional[Dict[str, DatasourcePackageIngestDetail]] = None


class DatasourcePackageIngestHistory(
    RootModel[Optional[Dict[str, LastIngestStateChangeDates]]]
):
    root: Optional[Dict[str, LastIngestStateChangeDates]] = None


class DeleteMembersResponse(BaseModel):
    AccountIds: Optional[AccountIdList] = None
    UnprocessedAccounts: Optional[UnprocessedAccountList] = None


class ListDatasourcePackagesResponse(BaseModel):
    DatasourcePackages: Optional[DatasourcePackageIngestDetails] = None
    NextToken: Optional[PaginationToken] = None


class ListTagsForResourceResponse(BaseModel):
    Tags: Optional[TagMap] = None


class MemberDetail(BaseModel):
    AccountId_1: Optional[AccountId] = Field(None, alias='AccountId')
    AdministratorId: Optional[AccountId] = None
    DatasourcePackageIngestStates_1: Optional[DatasourcePackageIngestStates] = Field(
        None, alias='DatasourcePackageIngestStates'
    )
    DisabledReason: Optional[MemberDisabledReason] = None
    EmailAddress_1: Optional[EmailAddress] = Field(None, alias='EmailAddress')
    GraphArn_1: Optional[GraphArn] = Field(None, alias='GraphArn')
    InvitationType_1: Optional[InvitationType] = Field(None, alias='InvitationType')
    InvitedTime: Optional[Timestamp] = None
    MasterId: Optional[AccountId] = None
    PercentOfGraphUtilization: Optional[Percentage] = None
    PercentOfGraphUtilizationUpdatedTime: Optional[Timestamp] = None
    Status: Optional[MemberStatus] = None
    UpdatedTime: Optional[Timestamp] = None
    VolumeUsageByDatasourcePackage_1: Optional[VolumeUsageByDatasourcePackage] = Field(
        None, alias='VolumeUsageByDatasourcePackage'
    )
    VolumeUsageInBytes: Optional[ByteValue] = None
    VolumeUsageUpdatedTime: Optional[Timestamp] = None


class MemberDetailList(RootModel[List[MemberDetail]]):
    root: List[MemberDetail]


class MembershipDatasources(BaseModel):
    AccountId_1: Optional[AccountId] = Field(None, alias='AccountId')
    DatasourcePackageIngestHistory_1: Optional[DatasourcePackageIngestHistory] = Field(
        None, alias='DatasourcePackageIngestHistory'
    )
    GraphArn_1: Optional[GraphArn] = Field(None, alias='GraphArn')


class MembershipDatasourcesList(RootModel[List[MembershipDatasources]]):
    root: List[MembershipDatasources]


class BatchGetGraphMemberDatasourcesResponse(BaseModel):
    MemberDatasources: Optional[MembershipDatasourcesList] = None
    UnprocessedAccounts: Optional[UnprocessedAccountList] = None


class BatchGetMembershipDatasourcesResponse(BaseModel):
    MembershipDatasources: Optional[MembershipDatasourcesList] = None
    UnprocessedGraphs: Optional[UnprocessedGraphList] = None


class CreateMembersResponse(BaseModel):
    Members: Optional[MemberDetailList] = None
    UnprocessedAccounts: Optional[UnprocessedAccountList] = None


class GetMembersResponse(BaseModel):
    MemberDetails: Optional[MemberDetailList] = None
    UnprocessedAccounts: Optional[UnprocessedAccountList] = None


class ListInvitationsResponse(BaseModel):
    Invitations: Optional[MemberDetailList] = None
    NextToken: Optional[PaginationToken] = None


class ListMembersResponse(BaseModel):
    MemberDetails: Optional[MemberDetailList] = None
    NextToken: Optional[PaginationToken] = None
